//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfTeenService.Entity.TeenData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeenNight
    {
        public int id { get; set; }
        public int TeenId { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string Decision { get; set; }
        public string Attended { get; set; }
    
        public virtual Teen Teen { get; set; }
    }
}
