//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfTeenService.Entity.TeenData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teen
    {
        public Teen()
        {
            this.GuestOf = "";
            this.TeenNights = new HashSet<TeenNight>();
        }
    
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneArea { get; set; }
        public string PhonePrefix { get; set; }
        public string PhonePostfix { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string zip { get; set; }
        public string Sex { get; set; }
        public string Bus { get; set; }
        public string Grade { get; set; }
        public string GuestOf { get; set; }
        public string GuestOfKey { get; set; }
    
        public virtual ICollection<TeenNight> TeenNights { get; set; }
    }
}
