//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeenProxy.wcfTeens {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teen", Namespace="")]
    [System.SerializableAttribute()]
    public partial class Teen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhonePrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhonePostfixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuestOfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuestOfKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool[] LstAttendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] LstDecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuestOfTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string PhoneArea {
            get {
                return this.PhoneAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneAreaField, value) != true)) {
                    this.PhoneAreaField = value;
                    this.RaisePropertyChanged("PhoneArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string PhonePrefix {
            get {
                return this.PhonePrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonePrefixField, value) != true)) {
                    this.PhonePrefixField = value;
                    this.RaisePropertyChanged("PhonePrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PhonePostfix {
            get {
                return this.PhonePostfixField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonePostfixField, value) != true)) {
                    this.PhonePostfixField = value;
                    this.RaisePropertyChanged("PhonePostfix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Street1 {
            get {
                return this.Street1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street1Field, value) != true)) {
                    this.Street1Field = value;
                    this.RaisePropertyChanged("Street1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Street2 {
            get {
                return this.Street2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street2Field, value) != true)) {
                    this.Street2Field = value;
                    this.RaisePropertyChanged("Street2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string zip {
            get {
                return this.zipField;
            }
            set {
                if ((object.ReferenceEquals(this.zipField, value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Bus {
            get {
                return this.BusField;
            }
            set {
                if ((object.ReferenceEquals(this.BusField, value) != true)) {
                    this.BusField = value;
                    this.RaisePropertyChanged("Bus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string GuestOf {
            get {
                return this.GuestOfField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestOfField, value) != true)) {
                    this.GuestOfField = value;
                    this.RaisePropertyChanged("GuestOf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string GuestOfKey {
            get {
                return this.GuestOfKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestOfKeyField, value) != true)) {
                    this.GuestOfKeyField = value;
                    this.RaisePropertyChanged("GuestOfKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public bool[] LstAttended {
            get {
                return this.LstAttendedField;
            }
            set {
                if ((object.ReferenceEquals(this.LstAttendedField, value) != true)) {
                    this.LstAttendedField = value;
                    this.RaisePropertyChanged("LstAttended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string[] LstDecision {
            get {
                return this.LstDecisionField;
            }
            set {
                if ((object.ReferenceEquals(this.LstDecisionField, value) != true)) {
                    this.LstDecisionField = value;
                    this.RaisePropertyChanged("LstDecision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string GuestOfTitle {
            get {
                return this.GuestOfTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestOfTitleField, value) != true)) {
                    this.GuestOfTitleField = value;
                    this.RaisePropertyChanged("GuestOfTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeenReport", Namespace="")]
    [System.SerializableAttribute()]
    public partial class TeenReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] lstNightTotalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] lstGuestTotalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeenTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GuestTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] lstNightTotals {
            get {
                return this.lstNightTotalsField;
            }
            set {
                if ((object.ReferenceEquals(this.lstNightTotalsField, value) != true)) {
                    this.lstNightTotalsField = value;
                    this.RaisePropertyChanged("lstNightTotals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int[] lstGuestTotals {
            get {
                return this.lstGuestTotalsField;
            }
            set {
                if ((object.ReferenceEquals(this.lstGuestTotalsField, value) != true)) {
                    this.lstGuestTotalsField = value;
                    this.RaisePropertyChanged("lstGuestTotals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int TeenTotal {
            get {
                return this.TeenTotalField;
            }
            set {
                if ((this.TeenTotalField.Equals(value) != true)) {
                    this.TeenTotalField = value;
                    this.RaisePropertyChanged("TeenTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int GuestTotal {
            get {
                return this.GuestTotalField;
            }
            set {
                if ((this.GuestTotalField.Equals(value) != true)) {
                    this.GuestTotalField = value;
                    this.RaisePropertyChanged("GuestTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeenRecord", Namespace="")]
    [System.SerializableAttribute()]
    public partial class TeenRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublicRecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PrivateRecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhonePrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneSuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuestOfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuestOfKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewRecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateCheckinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateRecField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublicRecId {
            get {
                return this.PublicRecIdField;
            }
            set {
                if ((this.PublicRecIdField.Equals(value) != true)) {
                    this.PublicRecIdField = value;
                    this.RaisePropertyChanged("PublicRecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PrivateRecId {
            get {
                return this.PrivateRecIdField;
            }
            set {
                if ((this.PrivateRecIdField.Equals(value) != true)) {
                    this.PrivateRecIdField = value;
                    this.RaisePropertyChanged("PrivateRecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string PhoneArea {
            get {
                return this.PhoneAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneAreaField, value) != true)) {
                    this.PhoneAreaField = value;
                    this.RaisePropertyChanged("PhoneArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string PhonePrefix {
            get {
                return this.PhonePrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonePrefixField, value) != true)) {
                    this.PhonePrefixField = value;
                    this.RaisePropertyChanged("PhonePrefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string PhoneSuffix {
            get {
                return this.PhoneSuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneSuffixField, value) != true)) {
                    this.PhoneSuffixField = value;
                    this.RaisePropertyChanged("PhoneSuffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Street1 {
            get {
                return this.Street1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street1Field, value) != true)) {
                    this.Street1Field = value;
                    this.RaisePropertyChanged("Street1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Street2 {
            get {
                return this.Street2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street2Field, value) != true)) {
                    this.Street2Field = value;
                    this.RaisePropertyChanged("Street2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string Bus {
            get {
                return this.BusField;
            }
            set {
                if ((object.ReferenceEquals(this.BusField, value) != true)) {
                    this.BusField = value;
                    this.RaisePropertyChanged("Bus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string GuestOf {
            get {
                return this.GuestOfField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestOfField, value) != true)) {
                    this.GuestOfField = value;
                    this.RaisePropertyChanged("GuestOf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string CheckIn {
            get {
                return this.CheckInField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckInField, value) != true)) {
                    this.CheckInField = value;
                    this.RaisePropertyChanged("CheckIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string Dirty {
            get {
                return this.DirtyField;
            }
            set {
                if ((object.ReferenceEquals(this.DirtyField, value) != true)) {
                    this.DirtyField = value;
                    this.RaisePropertyChanged("Dirty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string GuestOfKey {
            get {
                return this.GuestOfKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.GuestOfKeyField, value) != true)) {
                    this.GuestOfKeyField = value;
                    this.RaisePropertyChanged("GuestOfKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string NewRec {
            get {
                return this.NewRecField;
            }
            set {
                if ((object.ReferenceEquals(this.NewRecField, value) != true)) {
                    this.NewRecField = value;
                    this.RaisePropertyChanged("NewRec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string UpdateCheckin {
            get {
                return this.UpdateCheckinField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateCheckinField, value) != true)) {
                    this.UpdateCheckinField = value;
                    this.RaisePropertyChanged("UpdateCheckin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string UpdateRec {
            get {
                return this.UpdateRecField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateRecField, value) != true)) {
                    this.UpdateRecField = value;
                    this.RaisePropertyChanged("UpdateRec");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfTeens.ITeenService")]
    public interface ITeenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/HelloWorld", ReplyAction="http://tempuri.org/ITeenService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/LoadTeen", ReplyAction="http://tempuri.org/ITeenService/LoadTeenResponse")]
        TeenProxy.wcfTeens.Teen LoadTeen(int idx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetDistinctLastName", ReplyAction="http://tempuri.org/ITeenService/GetDistinctLastNameResponse")]
        string[] GetDistinctLastName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetDistinctFirstName", ReplyAction="http://tempuri.org/ITeenService/GetDistinctFirstNameResponse")]
        string[] GetDistinctFirstName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetDistinctZip", ReplyAction="http://tempuri.org/ITeenService/GetDistinctZipResponse")]
        string[] GetDistinctZip();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetDistinctCity", ReplyAction="http://tempuri.org/ITeenService/GetDistinctCityResponse")]
        string[] GetDistinctCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/DeleteTeen", ReplyAction="http://tempuri.org/ITeenService/DeleteTeenResponse")]
        void DeleteTeen(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetNextTeen", ReplyAction="http://tempuri.org/ITeenService/GetNextTeenResponse")]
        int GetNextTeen(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetPrevTeen", ReplyAction="http://tempuri.org/ITeenService/GetPrevTeenResponse")]
        int GetPrevTeen(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetFirstTeen", ReplyAction="http://tempuri.org/ITeenService/GetFirstTeenResponse")]
        int GetFirstTeen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetLastTeen", ReplyAction="http://tempuri.org/ITeenService/GetLastTeenResponse")]
        int GetLastTeen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetRecordsToId", ReplyAction="http://tempuri.org/ITeenService/GetRecordsToIdResponse")]
        int GetRecordsToId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/TotalTeenCount", ReplyAction="http://tempuri.org/ITeenService/TotalTeenCountResponse")]
        int TotalTeenCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetTeenReport", ReplyAction="http://tempuri.org/ITeenService/GetTeenReportResponse")]
        TeenProxy.wcfTeens.TeenReport GetTeenReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/ListGuestsBrought", ReplyAction="http://tempuri.org/ITeenService/ListGuestsBroughtResponse")]
        string[] ListGuestsBrought(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/ListTop5GuestBringers", ReplyAction="http://tempuri.org/ITeenService/ListTop5GuestBringersResponse")]
        System.Collections.Generic.KeyValuePair<TeenProxy.wcfTeens.Teen, int>[] ListTop5GuestBringers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/RealAllTeens", ReplyAction="http://tempuri.org/ITeenService/RealAllTeensResponse")]
        TeenProxy.wcfTeens.Teen[] RealAllTeens();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/SaveTeenRecord", ReplyAction="http://tempuri.org/ITeenService/SaveTeenRecordResponse")]
        TeenProxy.wcfTeens.Teen SaveTeenRecord(TeenProxy.wcfTeens.Teen teenData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/UpdateTeenRecord", ReplyAction="http://tempuri.org/ITeenService/UpdateTeenRecordResponse")]
        TeenProxy.wcfTeens.Teen UpdateTeenRecord(TeenProxy.wcfTeens.Teen teenData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetDecisionList", ReplyAction="http://tempuri.org/ITeenService/GetDecisionListResponse")]
        string[] GetDecisionList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetTeenByName", ReplyAction="http://tempuri.org/ITeenService/GetTeenByNameResponse")]
        TeenProxy.wcfTeens.Teen[] GetTeenByName(TeenProxy.wcfTeens.Teen teenData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetTeenByGuestOfKey", ReplyAction="http://tempuri.org/ITeenService/GetTeenByGuestOfKeyResponse")]
        TeenProxy.wcfTeens.Teen GetTeenByGuestOfKey(string GuestOfKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/DoWork", ReplyAction="http://tempuri.org/ITeenService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/ServerStatus", ReplyAction="http://tempuri.org/ITeenService/ServerStatusResponse")]
        string ServerStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/ServerStatusOptions", ReplyAction="http://tempuri.org/ITeenService/ServerStatusOptionsResponse")]
        void ServerStatusOptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/ProcessRecords", ReplyAction="http://tempuri.org/ITeenService/ProcessRecordsResponse")]
        string ProcessRecords(TeenProxy.wcfTeens.TeenRecord[] lstRecords);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/ProcessRecordsOptions", ReplyAction="http://tempuri.org/ITeenService/ProcessRecordsOptionsResponse")]
        void ProcessRecordsOptions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetRecords", ReplyAction="http://tempuri.org/ITeenService/GetRecordsResponse")]
        TeenProxy.wcfTeens.TeenRecord[] GetRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeenService/GetRecordsOptions", ReplyAction="http://tempuri.org/ITeenService/GetRecordsOptionsResponse")]
        void GetRecordsOptions();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeenServiceChannel : TeenProxy.wcfTeens.ITeenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeenServiceClient : System.ServiceModel.ClientBase<TeenProxy.wcfTeens.ITeenService>, TeenProxy.wcfTeens.ITeenService {
        
        public TeenServiceClient() {
        }
        
        public TeenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public TeenProxy.wcfTeens.Teen LoadTeen(int idx) {
            return base.Channel.LoadTeen(idx);
        }
        
        public string[] GetDistinctLastName() {
            return base.Channel.GetDistinctLastName();
        }
        
        public string[] GetDistinctFirstName() {
            return base.Channel.GetDistinctFirstName();
        }
        
        public string[] GetDistinctZip() {
            return base.Channel.GetDistinctZip();
        }
        
        public string[] GetDistinctCity() {
            return base.Channel.GetDistinctCity();
        }
        
        public void DeleteTeen(int id) {
            base.Channel.DeleteTeen(id);
        }
        
        public int GetNextTeen(int id) {
            return base.Channel.GetNextTeen(id);
        }
        
        public int GetPrevTeen(int id) {
            return base.Channel.GetPrevTeen(id);
        }
        
        public int GetFirstTeen() {
            return base.Channel.GetFirstTeen();
        }
        
        public int GetLastTeen() {
            return base.Channel.GetLastTeen();
        }
        
        public int GetRecordsToId(int id) {
            return base.Channel.GetRecordsToId(id);
        }
        
        public int TotalTeenCount() {
            return base.Channel.TotalTeenCount();
        }
        
        public TeenProxy.wcfTeens.TeenReport GetTeenReport() {
            return base.Channel.GetTeenReport();
        }
        
        public string[] ListGuestsBrought(int id) {
            return base.Channel.ListGuestsBrought(id);
        }
        
        public System.Collections.Generic.KeyValuePair<TeenProxy.wcfTeens.Teen, int>[] ListTop5GuestBringers() {
            return base.Channel.ListTop5GuestBringers();
        }
        
        public TeenProxy.wcfTeens.Teen[] RealAllTeens() {
            return base.Channel.RealAllTeens();
        }
        
        public TeenProxy.wcfTeens.Teen SaveTeenRecord(TeenProxy.wcfTeens.Teen teenData) {
            return base.Channel.SaveTeenRecord(teenData);
        }
        
        public TeenProxy.wcfTeens.Teen UpdateTeenRecord(TeenProxy.wcfTeens.Teen teenData) {
            return base.Channel.UpdateTeenRecord(teenData);
        }
        
        public string[] GetDecisionList() {
            return base.Channel.GetDecisionList();
        }
        
        public TeenProxy.wcfTeens.Teen[] GetTeenByName(TeenProxy.wcfTeens.Teen teenData) {
            return base.Channel.GetTeenByName(teenData);
        }
        
        public TeenProxy.wcfTeens.Teen GetTeenByGuestOfKey(string GuestOfKey) {
            return base.Channel.GetTeenByGuestOfKey(GuestOfKey);
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public string ServerStatus() {
            return base.Channel.ServerStatus();
        }
        
        public void ServerStatusOptions() {
            base.Channel.ServerStatusOptions();
        }
        
        public string ProcessRecords(TeenProxy.wcfTeens.TeenRecord[] lstRecords) {
            return base.Channel.ProcessRecords(lstRecords);
        }
        
        public void ProcessRecordsOptions() {
            base.Channel.ProcessRecordsOptions();
        }
        
        public TeenProxy.wcfTeens.TeenRecord[] GetRecords() {
            return base.Channel.GetRecords();
        }
        
        public void GetRecordsOptions() {
            base.Channel.GetRecordsOptions();
        }
    }
}
